In [1]:
import numpy as np

In [2]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

### matrix multiplication

In [3]:
print(arr1.dot(arr2))
# or
print()
print(np.dot(arr1, arr2))
# or
print()
print(arr1 @ arr2)

[[1.1323315  1.4871555  1.37449847 0.76084655 1.43381324]
 [0.74120733 1.88369104 1.30696804 1.37404845 0.81301393]
 [0.61785424 1.5775929  1.01666317 1.2917662  0.76733341]
 [0.75206867 1.20030851 0.869281   0.87378849 1.193709  ]
 [0.92494678 2.04286839 1.54019997 1.40407787 0.8767349 ]]

[[1.1323315  1.4871555  1.37449847 0.76084655 1.43381324]
 [0.74120733 1.88369104 1.30696804 1.37404845 0.81301393]
 [0.61785424 1.5775929  1.01666317 1.2917662  0.76733341]
 [0.75206867 1.20030851 0.869281   0.87378849 1.193709  ]
 [0.92494678 2.04286839 1.54019997 1.40407787 0.8767349 ]]

[[1.1323315  1.4871555  1.37449847 0.76084655 1.43381324]
 [0.74120733 1.88369104 1.30696804 1.37404845 0.81301393]
 [0.61785424 1.5775929  1.01666317 1.2917662  0.76733341]
 [0.75206867 1.20030851 0.869281   0.87378849 1.193709  ]
 [0.92494678 2.04286839 1.54019997 1.40407787 0.8767349 ]]


### QR factorization 

In [5]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.16299107  0.68625716 -0.58669582  0.34979941  0.18950832]
 [-0.55068887  0.16763092  0.6558674   0.31027815  0.37710354]
 [-0.57095308 -0.64850834 -0.45751381  0.18642062  0.09683996]
 [-0.51112775  0.23923513  0.05614426 -0.17763146 -0.8042449 ]
 [-0.2879873   0.1521659  -0.11469486 -0.84561354  0.40705242]]
[[-1.74673898 -1.17686217 -0.99607184 -0.87120603 -1.26176352]
 [ 0.          0.89077423  0.02318318 -0.04275573  0.36526156]
 [ 0.          0.         -0.75288309 -0.58553633 -0.25977118]
 [ 0.          0.          0.          0.03961789 -0.29277405]
 [ 0.          0.          0.          0.          0.39517443]]


### singular value decomposition (SVD)

In [5]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-0.51582413  0.05340736 -0.69571428 -0.42334918  0.26044237]
 [-0.34775725 -0.842141    0.21629222  0.15550346  0.31448335]
 [-0.58401574  0.12177925  0.51003396 -0.4015491  -0.47193125]
 [-0.19493532  0.47928268  0.41313699  0.07759931  0.74537541]
 [-0.48364882  0.20833652 -0.19591453  0.79330374 -0.23444912]]
[2.96018519 0.93273137 0.62401273 0.40194888 0.26704925]
[[-0.48078664 -0.39309221 -0.42944155 -0.29921415 -0.58341544]
 [ 0.48711506 -0.50981326  0.52113532  0.06743482 -0.4761091 ]
 [-0.01840113  0.30579164 -0.20481209  0.81028409 -0.45568033]
 [ 0.00896271 -0.69463434 -0.31862447  0.44454422  0.46718486]
 [-0.7287964  -0.09769114  0.63287312  0.22747212  0.08390644]]


### compute eigen values

In [3]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 2.75947165+0.j          0.53460399+0.j         -0.14472386+0.53197177j
 -0.14472386-0.53197177j -0.38947526+0.j        ]


### eigen value decomposition

In [7]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.0705397 +0.j         -0.09856237+0.39940682j -0.09856237-0.39940682j
  0.48908525+0.j          0.28863039+0.j        ]
[[-0.31361687+0.j          0.35620334+0.32834851j  0.35620334-0.32834851j
   0.51233624+0.j         -0.02518616+0.j        ]
 [-0.36777171+0.j         -0.09653469+0.26202164j -0.09653469-0.26202164j
  -0.72771843+0.j          0.55066967+0.j        ]
 [-0.62159923+0.j          0.19652303-0.30937207j  0.19652303+0.30937207j
  -0.3036553 +0.j          0.55726531+0.j        ]
 [-0.34511238+0.j          0.01968525-0.26925958j  0.01968525+0.26925958j
   0.29933888+0.j         -0.5831596 +0.j        ]
 [-0.51078397+0.j         -0.69290081+0.j         -0.69290081-0.j
   0.16163899+0.j         -0.21332796+0.j        ]]


### compute the trace & determinant

In [8]:
# notice this is not a function in linalg!!!
print(np.trace(arr))    

2.651130601170305


In [6]:
print(np.linalg.det(arr))

0.018340168932605955


### calculate the inverse/psedo-inverse of a matrix

In [7]:
arr = np.random.rand(5,5)

In [8]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[ 11.95533897   7.43444569   6.70020593 -10.40085946 -15.82347925]
 [-18.73898506 -12.29929884  -9.55474973  15.12551606  26.55816614]
 [  8.14593402   4.87018744   6.12419815  -7.2549003  -12.37027716]
 [ -1.86689274   0.80949568  -2.00748791   2.16159669   1.24758553]
 [ -5.79874743  -4.38071287  -4.06485999   6.02284908   9.34564617]]


In [9]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[ 11.95533897   7.43444569   6.70020593 -10.40085946 -15.82347925]
 [-18.73898506 -12.29929884  -9.55474973  15.12551606  26.55816614]
 [  8.14593402   4.87018744   6.12419815  -7.2549003  -12.37027716]
 [ -1.86689274   0.80949568  -2.00748791   2.16159669   1.24758553]
 [ -5.79874743  -4.38071287  -4.06485999   6.02284908   9.34564617]]


### solve a linear system

In [13]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[ 2.80616855  4.25112878 -1.06728394  1.74226111 -1.34895981]


In [14]:
# calculate the least-squares solution of a linear system
y = [1,2,3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[ 2.80616855  4.25112878 -1.06728394  1.74226111 -1.34895981]
[]
5
[2.45425469 0.89773066 0.73143991 0.57608405 0.10952437]


C:\Users\ewang\AppData\Local\Continuum\miniconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until
